server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: auth-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:${KEYCLOAK_SERVER_URL:http://keycloak:8080}/realms/${KEYCLOAK_REALM:shopifake}}
          jwk-set-uri: ${KEYCLOAK_JWK_SET_URI:${KEYCLOAK_SERVER_URL:http://keycloak:8080}/realms/${KEYCLOAK_REALM:shopifake}/protocol/openid-connect/certs}

keycloak:
  server-url: ${KEYCLOAK_SERVER_URL:http://keycloak:8080}
  realm: ${KEYCLOAK_REALM:shopifake}
  client-id: ${KEYCLOAK_CLIENT_ID:shopifake-client}
  client-secret: ${KEYCLOAK_CLIENT_SECRET:your-client-secret}
  admin-username: ${KEYCLOAK_ADMIN_USERNAME:admin}
  admin-password: ${KEYCLOAK_ADMIN_PASSWORD:admin}

app:
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS:http://localhost:3000,http://localhost:8080}

logging:
  level:
    org.springframework.security: ${LOGGING_LEVEL_SECURITY:DEBUG}
    org.keycloak: ${LOGGING_LEVEL_KEYCLOAK:INFO}
